"use client";
import React, { useMemo, useState } from "react";
import { BadgeCheck, Banknote, Check, Download, FileText, Landmark } from "lucide-react";
import { useStore } from "@/lib/store";
import { downloadCsv, fmtMoney } from "@/lib/data";
import { Badge, Reveal } from "@/components/ui";
import type { PayoutPeriod } from "@/lib/types";

const TONE: Record<PayoutPeriod["status"], "gold" | "violet" | "mint"> = {
  pending: "gold", approved: "violet", paid: "mint",
};

export default function PayoutsPage() {
  const store = useStore();
  const isAdmin = store.user?.role === "admin";
  const [statusF, setStatusF] = useState<"all" | PayoutPeriod["status"]>("all");

  const rows = useMemo(() => {
    const scoped = isAdmin ? store.payoutPeriods : store.payoutPeriods.filter((p) => p.publisherId === store.user?.id || p.publisherId === "u_pub");
    return statusF === "all" ? scoped : scoped.filter((p) => p.status === statusF);
  }, [store.payoutPeriods, statusF, isAdmin, store.user?.id]);

  const totals = useMemo(() => ({
    pending: rows.filter((r) => r.status === "pending").reduce((a, r) => a + r.net, 0),
    approved: rows.filter((r) => r.status === "approved").reduce((a, r) => a + r.net, 0),
    paid: rows.filter((r) => r.status === "paid").reduce((a, r) => a + r.net, 0),
  }), [rows]);

  const statement = (p: PayoutPeriod) => {
    const body = [
      "REVBOUNCE LABS — EARNINGS STATEMENT", "─".repeat(42),
      `Statement:  ${p.id}`, `Period:     ${p.period}`, `Publisher:  ${p.publisher}`, "",
      `Gross revenue:      ${fmtMoney(p.gross, 2)}`,
      `Publisher split:    ${p.split}%`,
      `Platform fee:       ${fmtMoney(p.gross - p.net, 2)}`,
      `NET PAYABLE:        ${fmtMoney(p.net, 2)}`, "",
      `Method:     ${p.method}`, `Status:     ${p.status.toUpperCase()}`, "",
      "Generated by RevBounce · turn traffic into revenue.",
    ].join("\n");
    const blob = new Blob([body], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `${p.id}-statement.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
    store.toast(`Statement ${p.id} downloaded`);
  };

  return (
    <div className="space-y-6">
      <Reveal className="flex flex-wrap items-end gap-3">
        <div>
          <h1 className="font-display text-3xl">Payouts</h1>
          <p className="text-sm text-[#8b8794] mt-1">
            {isAdmin ? "Approve periods and mark them paid. Splits apply automatically." : "Earnings by period, approval status and downloadable statements."}
          </p>
        </div>
        <div className="ml-auto flex gap-2">
          <select className="input-lux !w-auto" value={statusF} onChange={(e) => setStatusF(e.target.value as typeof statusF)}>
            <option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="paid">Paid</option>
          </select>
          <button onClick={() => {
            downloadCsv("revbounce-payouts.csv", rows.map((r) => ({
              id: r.id, period: r.period, publisher: r.publisher, gross: r.gross.toFixed(2),
              split_pct: r.split, net: r.net.toFixed(2), status: r.status, method: r.method,
            })));
            store.toast(`Exported ${rows.length} payout rows`);
          }} className="btn-gold rounded-xl px-4 py-2.5 text-sm flex items-center gap-2"><Download size={14} /> Export CSV</button>
        </div>
      </Reveal>

      <div className="grid sm:grid-cols-3 gap-4">
        {([
          ["Pending approval", totals.pending, "gold", Landmark],
          ["Approved · awaiting wire", totals.approved, "violet", BadgeCheck],
          ["Paid to date", totals.paid, "mint", Banknote],
        ] as const).map(([l, v, tone, Icon]) => (
          <Reveal key={l} className="glass rounded-2xl p-5">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs text-[#8b8794]">{l}</span><Icon size={16} className="text-[#d9b380]" />
            </div>
            <p className="font-display text-[26px]">{fmtMoney(v, 2)}</p>
            <div className="mt-2"><Badge tone={tone}>{rows.filter((r) => (l.startsWith("Pending") ? r.status === "pending" : l.startsWith("Approved") ? r.status === "approved" : r.status === "paid")).length} periods</Badge></div>
          </Reveal>
        ))}
      </div>

      <Reveal className="glass rounded-2xl p-2 sm:p-4">
        <div className="overflow-x-auto">
          <table className="w-full text-sm min-w-[880px]">
            <thead>
              <tr className="text-left text-[10px] tracking-[0.2em] uppercase text-[#5d5867] border-b border-line">
                <th className="pb-3 pl-2 font-medium">Period</th>
                {isAdmin && <th className="pb-3 font-medium">Publisher</th>}
                <th className="pb-3 font-medium text-right">Gross</th><th className="pb-3 font-medium text-right">Split</th>
                <th className="pb-3 font-medium text-right">Net payable</th><th className="pb-3 font-medium">Method</th>
                <th className="pb-3 font-medium">Status</th><th className="pb-3 font-medium text-right pr-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((p) => (
                <tr key={p.id} className="border-b border-line/50 last:border-0 hover:bg-white/[0.02] transition">
                  <td className="py-3.5 pl-2 pr-4">
                    <p className="text-[13px]">{p.period}</p><p className="text-[10.5px] text-[#5d5867] font-mono">{p.id}</p>
                  </td>
                  {isAdmin && <td className="py-3.5 pr-4 text-[12.5px] text-[#c9c4b8]">{p.publisher}</td>}
                  <td className="py-3.5 pr-4 text-right tabular-nums text-[#97919f]">{fmtMoney(p.gross, 2)}</td>
                  <td className="py-3.5 pr-4 text-right tabular-nums text-[#c9c4b8]">{p.split}%</td>
                  <td className="py-3.5 pr-4 text-right tabular-nums font-semibold text-[#f0d9ae]">{fmtMoney(p.net, 2)}</td>
                  <td className="py-3.5 pr-4 text-[11.5px] text-[#97919f]">{p.method}</td>
                  <td className="py-3.5 pr-4"><Badge tone={TONE[p.status]}>{p.status.toUpperCase()}</Badge></td>
                  <td className="py-3.5 pr-2">
                    <div className="flex gap-1.5 justify-end">
                      <button onClick={() => statement(p)} className="btn-ghost rounded-lg px-2.5 py-1.5 text-[11px] inline-flex items-center gap-1.5">
                        <FileText size={11} /> Statement
                      </button>
                      {isAdmin && p.status === "pending" && (
                        <button onClick={() => { store.setPayoutStatus(p.id, "approved"); store.toast(`${p.publisher} · ${p.period} approved`); }}
                          className="rounded-lg px-2.5 py-1.5 text-[11px] bg-[rgba(139,124,240,.14)] border border-[rgba(139,124,240,.35)] text-[#b3a6f5] hover:bg-[rgba(139,124,240,.24)] transition inline-flex items-center gap-1.5">
                          <Check size={11} /> Approve
                        </button>
                      )}
                      {isAdmin && p.status === "approved" && (
                        <button onClick={() => { store.setPayoutStatus(p.id, "paid"); store.toast(`${p.publisher} · ${fmtMoney(p.net, 2)} marked paid`); }}
                          className="rounded-lg px-2.5 py-1.5 text-[11px] bg-[rgba(143,227,176,.14)] border border-[rgba(143,227,176,.35)] text-[#8fe3b0] hover:bg-[rgba(143,227,176,.24)] transition inline-flex items-center gap-1.5">
                          <Banknote size={11} /> Mark paid
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {rows.length === 0 && <p className="text-center text-sm text-[#8b8794] py-10">No payout periods match this filter.</p>}
      </Reveal>

      {!isAdmin && (
        <Reveal className="glass rounded-2xl px-6 py-5 flex flex-wrap items-center gap-4">
          <span className="w-10 h-10 rounded-xl bg-[rgba(217,179,128,.1)] border border-line flex items-center justify-center text-[#d9b380]"><Landmark size={18} /></span>
          <p className="text-xs text-[#a49ea8] flex-1 min-w-[240px] leading-relaxed">
            Paid twice monthly to <b className="text-[#c9c4b8]">{store.payoutDetails.handle}</b> ({store.payoutDetails.method.toUpperCase()}), once your balance clears {fmtMoney(store.payoutDetails.minimumPayout)}.
            Tax form {store.payoutDetails.taxFormOnFile ? "is on file" : "is missing — payouts hold until received"}.
          </p>
          <a href="/dashboard/publishers" className="btn-ghost rounded-xl px-4 py-2.5 text-xs">Update payout details</a>
        </Reveal>
      )}
    </div>
  );
}
